### ISSUE TITLE
How to correctly generate training data?

### ISSUE THREAD

**Issue by Roboxkin** [Azazel0203/ocr_captcha#1]
Hello!
How to correctly generate training data?

Please tell us in more detail what files are needed and what structure
Thank you

P.S. Not all dependencies are installed
P.P.S. labels? How to create them correctly?

![ANTIBOT_MODULE_captcha](https://github.com/Azazel0203/ocr_captcha/assets/39112555/7cfaf380-fd94-49a7-95d7-2264cc46da10)

![ANTIBOT_MODULE_captcha](https://github.com/Azazel0203/ocr_captcha/assets/39112555/42b53fa0-66da-4c4f-8ef3-3298e0345e64)

**Comment by Azazel0203** [comment]
> Hello! How to correctly generate training data?
> 
> Please tell us in more detail what files are needed and what structure Thank you
> 
> P.S. Not all dependencies are installed P.P.S. labels? How to create them correctly?
> 
> ![ANTIBOT_MODULE_captcha](https://private-user-images.githubusercontent.com/39112555/328068306-7cfaf380-fd94-49a7-95d7-2264cc46da10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NjYwODAsIm5iZiI6MTcxNDk2NTc4MCwicGF0aCI6Ii8zOTExMjU1NS8zMjgwNjgzMDYtN2NmYWYzODAtZmQ5NC00OWE3LTk1ZDctMjI2NGNjNDZkYTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDAzMjMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhNzM0ZjMxNDA0ZmZmNjBiOGFhOWU4MmFmMDQxZDUzMDk2ZGFiNDllYTMwZDlkYzMyOGM2OWVkZDFjNmFmNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JfG8f49aUU5nOun0cFUl9DDEXmVcfm6kSK4uHy7YTmk)
> 
> ![ANTIBOT_MODULE_captcha](https://private-user-images.githubusercontent.com/39112555/328068473-42b53fa0-66da-4c4f-8ef3-3298e0345e64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NjYwODAsIm5iZiI6MTcxNDk2NTc4MCwicGF0aCI6Ii8zOTExMjU1NS8zMjgwNjg0NzMtNDJiNTNmYTAtNjZkYS00YzRmLThlZjMtMzI5OGUwMzQ1ZTY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDAzMjMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiN2NhMWVjODUxNDg2ZGI3MGFjODYyNTVlYzE2ZGFlMDExZTI1NGYzMTBhMDVhMmJjZjFkN2UyMmI1MmMzYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q9ZC71zO_rnlwYml0I4tYq1j5bcGLg5bhvEvgdhuYbA)

For Images formatted like this
![image](https://github.com/Azazel0203/ocr_captcha/assets/139248351/5e888763-0dc0-4804-9a2d-0d2c45aa90b8)
The csv file should be formatted like this
![image](https://github.com/Azazel0203/ocr_captcha/assets/139248351/0008bb69-d6f1-4172-9ae3-6230b68ac554)


And regarding file structure..
![image](https://github.com/Azazel0203/ocr_captcha/assets/139248351/83a174e1-0d86-4ba4-92fc-aa4328d36730)
Thats under the 'data' folder

**Comment by Roboxkin** [comment]
Thank you very much for the answer!
Thank you very much for the work done and the project provided!
I hope that you will not abandon it and will develop it.
This is the best thing I've seen on GIT
